# Generated by Django 6.0 on 2025-12-03 21:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField(blank=True)),
                ('event_date', models.DateField(blank=True, help_text='Planned event date', null=True)),
                ('contact_method', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('in-app', 'In-App')], default='phone', max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=10)),
                ('source', models.CharField(choices=[('search', 'Search'), ('featured', 'Featured'), ('ad', 'Advertisement'), ('direct', 'Direct')], default='search', max_length=10)),
                ('billed', models.BooleanField(default=False, help_text='Whether this lead has been billed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='Null if guest user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='vendors.vendor')),
            ],
            options={
                'db_table': 'leads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vendor', 'status'], name='leads_vendor__b67330_idx'), models.Index(fields=['created_at'], name='leads_created_e6e479_idx')],
            },
        ),
    ]
