# Generated by Django 6.0 on 2026-03-22 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='event_type',
            field=models.CharField(blank=True, choices=[('wedding', 'Wedding'), ('birthday', 'Birthday Party'), ('corporate', 'Corporate Event'), ('burial', 'Burial / Funeral'), ('graduation', 'Graduation'), ('baby_shower', 'Baby Shower'), ('engagement', 'Engagement'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes for vendor use only'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='contact_method',
            field=models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('in-app', 'In-App')], default='phone', max_length=15),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('search', 'Search'), ('featured', 'Featured'), ('ad', 'Advertisement'), ('direct', 'Direct'), ('phone_reveal', 'Phone Reveal')], default='search', max_length=15),
        ),
    ]
