# Generated by Django 6.0 on 2025-12-07 11:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0003_successstory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conversation_code', models.CharField(editable=False, help_text='Unique code to identify this conversation', max_length=12, unique=True)),
                ('event_type', models.CharField(blank=True, help_text='e.g., wedding, birthday, corporate', max_length=100)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('location', models.CharField(blank=True, help_text='City or neighborhood', max_length=200)),
                ('guest_count', models.IntegerField(blank=True, null=True)),
                ('vendor_types_needed', models.JSONField(blank=True, default=list, help_text='List of vendor categories needed')),
                ('special_requirements', models.TextField(blank=True, help_text='Any special needs or preferences')),
                ('session_id', models.CharField(blank=True, help_text='Browser session ID', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False, help_text='Has the conversation finished?')),
                ('recommendations_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='Logged-in user (null if guest)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_conversations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('token_count', models.IntegerField(blank=True, help_text='OpenAI tokens used', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatconversation')),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True, help_text='AI explanation for recommendation')),
                ('match_score', models.IntegerField(default=0, help_text='Relevance score (0-100)')),
                ('viewed', models.BooleanField(default=False, help_text='Did user view this vendor?')),
                ('contacted', models.BooleanField(default=False, help_text='Did user contact this vendor?')),
                ('favorited', models.BooleanField(default=False, help_text='Did user favorite this vendor?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='chatbot.chatconversation')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_recommendations', to='vendors.vendor')),
            ],
            options={
                'db_table': 'chat_recommendations',
                'ordering': ['-match_score', 'vendor__name'],
            },
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['conversation_code'], name='chat_conver_convers_5df14c_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['created_at'], name='chat_conver_created_62f1ed_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['is_completed'], name='chat_conver_is_comp_942a4b_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='chat_messag_convers_0a903c_idx'),
        ),
        migrations.AddIndex(
            model_name='chatrecommendation',
            index=models.Index(fields=['conversation', 'match_score'], name='chat_recomm_convers_72034b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatrecommendation',
            unique_together={('conversation', 'vendor')},
        ),
    ]
