# Generated by Django 6.0 on 2025-12-03 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boost',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boosts', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.subscriptionplan'),
        ),
        migrations.AddIndex(
            model_name='boost',
            index=models.Index(fields=['vendor', 'is_active'], name='boosts_vendor__8d7702_idx'),
        ),
        migrations.AddIndex(
            model_name='boost',
            index=models.Index(fields=['start_date', 'end_date'], name='boosts_start_d_082edb_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['vendor', 'status'], name='subscriptio_vendor__b64c52_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['renewal_date'], name='subscriptio_renewal_60db3c_idx'),
        ),
    ]
