# Generated by Django 6.0 on 2025-12-03 21:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(default='Accra', max_length=100)),
                ('neighborhood', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('social_links', models.JSONField(blank=True, default=dict, help_text='JSON object with instagram, facebook, twitter keys')),
                ('images', models.JSONField(blank=True, default=list, help_text='Array of image URLs')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Array of tags')),
                ('price_tier', models.CharField(choices=[('low', 'Low (₵)'), ('medium', 'Medium (₵₵)'), ('high', 'High (₵₵₵)')], default='medium', max_length=10)),
                ('estimated_price_range', models.CharField(blank=True, help_text="e.g. '₵500 - ₵2000'", max_length=100)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('reviews_count', models.IntegerField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended')], default='pending', max_length=10)),
                ('views_count', models.IntegerField(default=0)),
                ('leads_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendors', to='categories.category')),
                ('subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='billing.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vendors',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'verified'], name='vendors_status_9375d1_idx'), models.Index(fields=['category', 'city'], name='vendors_categor_972eac_idx'), models.Index(fields=['slug'], name='vendors_slug_5bb22c_idx')],
            },
        ),
    ]
