# Generated by Django 6.0 on 2025-12-07 11:04

import django.db.models.deletion
import uuid
import vendors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(max_length=500, upload_to=vendors.models.vendor_image_upload_path)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary image displayed in listings')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower number = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_images', to='vendors.vendor')),
            ],
            options={
                'db_table': 'vendor_images',
                'ordering': ['-is_primary', 'order', '-created_at'],
                'indexes': [models.Index(fields=['vendor', 'is_primary'], name='vendor_imag_vendor__4c2ee5_idx'), models.Index(fields=['vendor', 'order'], name='vendor_imag_vendor__c87467_idx')],
            },
        ),
    ]
